name = "levity-ethics-systems"
main = "functions/index.ts"
compatibility_date = "2026-10-05"

[observability]
enabled = true

[vars]
APP_NAME = "Levity Ethics Systems"
APP_ENV = "development"

[[d1_databases]]
binding = "DB"
database_name = "levity-ethics-systems-db"
database_id = "5e9486ab-6791-47e6-ae90-933970b16f07"
migrations_dir = "database/migrations"
