import type { UserRole } from "../types/index.js";
import { PERMISSIONS, type Permission } from "./permissions.js";

/**
 * Levity Ethics Systems
 *
 * Central role-to-permission map.
 *
 * IMPORTANT:
 * Permissions are defined separately in permissions.ts.
 * Roles are defined separately in roles.ts.
 * This file connects them together.
 */

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  // ==================================================
  // PLATFORM
  // ==================================================

  super_admin: [
    PERMISSIONS.PLATFORM_MANAGE,
    PERMISSIONS.PLATFORM_VIEW,

    PERMISSIONS.SCHOOL_CREATE,
    PERMISSIONS.SCHOOL_VIEW,
    PERMISSIONS.SCHOOL_UPDATE,
    PERMISSIONS.SCHOOL_DELETE,

    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_SUSPEND,

    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,

    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_DELETE,

    PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.ACADEMICS_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_VIEW,
    PERMISSIONS.EXAM_UPDATE,

    PERMISSIONS.RESULT_CREATE,
    PERMISSIONS.RESULT_VIEW,
    PERMISSIONS.RESULT_UPDATE,

    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_MANAGE,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_MANAGE,

    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT
  ],

  // ==================================================
  // SCHOOL OWNER
  // ==================================================

  school_owner: [
    PERMISSIONS.SCHOOL_VIEW,
    PERMISSIONS.SCHOOL_UPDATE,

    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_SUSPEND,

    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,

    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_DELETE,

    PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.ACADEMICS_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_VIEW,
    PERMISSIONS.EXAM_UPDATE,

    PERMISSIONS.RESULT_CREATE,
    PERMISSIONS.RESULT_VIEW,
    PERMISSIONS.RESULT_UPDATE,

    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_MANAGE,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_MANAGE,

    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT
  ],

  // ==================================================
  // SCHOOL ADMINISTRATOR
  // ==================================================

  school_admin: [
    PERMISSIONS.SCHOOL_VIEW,
    PERMISSIONS.SCHOOL_UPDATE,

    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_UPDATE,

    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_UPDATE,

    PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.ACADEMICS_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_VIEW,
    PERMISSIONS.EXAM_UPDATE,

    PERMISSIONS.RESULT_CREATE,
    PERMISSIONS.RESULT_VIEW,
    PERMISSIONS.RESULT_UPDATE,

    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_MANAGE,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_MANAGE,

    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT
  ],

  // ==================================================
  // PRINCIPAL
  // ==================================================

  principal: [
    PERMISSIONS.SCHOOL_VIEW,

    PERMISSIONS.USER_VIEW,

    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_UPDATE,

    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_UPDATE,

    PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.ACADEMICS_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_VIEW,
    PERMISSIONS.EXAM_UPDATE,

    PERMISSIONS.RESULT_CREATE,
    PERMISSIONS.RESULT_VIEW,
    PERMISSIONS.RESULT_UPDATE,

    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.PAYMENT_VIEW,

    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT
  ],

  // ==================================================
  // VICE PRINCIPAL
  // ==================================================

  vice_principal: [
    PERMISSIONS.SCHOOL_VIEW,

    PERMISSIONS.USER_VIEW,

    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_UPDATE,

    PERMISSIONS.STAFF_VIEW,

    PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.ACADEMICS_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.EXAM_CREATE,
    PERMISSIONS.EXAM_VIEW,

    PERMISSIONS.RESULT_CREATE,
    PERMISSIONS.RESULT_VIEW,
    PERMISSIONS.RESULT_UPDATE,

    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,

    PERMISSIONS.REPORT_VIEW
  ],

  // ==================================================
  // TEACHER
  // ==================================================

  teacher: [
    PERMISSIONS.SCHOOL_VIEW,

    PERMISSIONS.STUDENT_VIEW,

    PERMISSIONS.ACADEMICS_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.EXAM_VIEW,

    PERMISSIONS.RESULT_CREATE,
    PERMISSIONS.RESULT_VIEW,
    PERMISSIONS.RESULT_UPDATE,

    PERMISSIONS.ANNOUNCEMENT_VIEW,

    PERMISSIONS.REPORT_VIEW
  ],

  // ==================================================
  // BURSAR
  // ==================================================

  bursar: [
    PERMISSIONS.SCHOOL_VIEW,

    PERMISSIONS.STUDENT_VIEW,

    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_MANAGE,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_MANAGE,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT
  ],

  // ==================================================
  // GENERAL STAFF
  // ==================================================

  staff: [
    PERMISSIONS.SCHOOL_VIEW,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_VIEW
  ],

  // ==================================================
  // STUDENT
  // ==================================================

  student: [
    PERMISSIONS.SCHOOL_VIEW,

    PERMISSIONS.ACADEMICS_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,

    PERMISSIONS.EXAM_VIEW,

    PERMISSIONS.RESULT_VIEW,

    PERMISSIONS.ANNOUNCEMENT_VIEW
  ],

  // ==================================================
  // PARENT / GUARDIAN
  // ==================================================

  parent: [
    PERMISSIONS.SCHOOL_VIEW,

    PERMISSIONS.STUDENT_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,

    PERMISSIONS.RESULT_VIEW,

    PERMISSIONS.FEES_VIEW,

    PERMISSIONS.PAYMENT_VIEW,

    PERMISSIONS.ANNOUNCEMENT_VIEW
  ]
};
